### ISSUE TITLE
Integrate jirecon to jitisi meet application

### ISSUE THREAD

**Issue by shehrozekhan** [jitsi/jirecon#16]
I can't find documentation to integrate jirecon to the jitsi meet application. I want to execute the jirecon.sh script from the record button on the jitsi UI but I am not sure what parameters need to be given as per requirement. Alternatively, or I just need to execute the shell script on the HTML button on UI?

**Comment by bgrozev** [comment]
This project is not in use anymore, and doesn't work with current versions of jitsi-meet.

**Comment by bgrozev** [comment]
Use jibri instead: https://github.com/jitsi/jibri
